name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # This targets your Raspberry Pi runner
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy Docker image
        env:
          TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
        run: |
          docker build -t ic-bot .
          docker stop ic-bot || true
          docker rm ic-bot || true
          docker run -d --name ic-bot \
            -e TELOXIDE_TOKEN=$TELOXIDE_TOKEN \
            ic-bot