name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy Docker image
        env:
          TELOXIDE_TOKEN: ${{ secrets.TELOXIDE_TOKEN }}
        run: |
          sudo docker build -t ic-bot .
          sudo docker stop ic-bot || true
          sudo docker rm ic-bot || true
          sudo docker run -dt --name ic-bot \
            -e TELOXIDE_TOKEN=$TELOXIDE_TOKEN \
            ic-bot